<?php
/**
* Implements hook_field_formatter_info().
*/
function extrajsfieldformatter_field_formatter_info() {
  return array(
    'field_extrajsfieldformatter' => array(
      'label' => t('Call javascript file'),
      'field types' => array('file'),
      'description' => t('Takes the path given in a file field and uses a drupal_get_js()'),
    ),
  );

}

/**
* Implements hook_field_formatter_view().
*/
function extrajsfieldformatter_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {

	$file_path_to_insert = file_create_url($items[0]['uri']);

	if (preg_match("js$", $file_path_to_insert)) {
		drupal_add_js($file_path_to_insert);
		$element[0]['#markup'] = "<code> DEBUG JS adding $file_path_to_insert </code>";
	elseif (preg_match("css$", $file_path_to_insert))
		drupal_add_css($file_path_to_insert);
		$element[0]['#markup'] = "<code> DEBUG CSS adding $file_path_to_insert </code>";
	
	return $element;
}

