<?php
/**
* Implements hook_field_formatter_info().
*/
function extrajsfieldformatter_field_formatter_info() {
  return array(
    'field_extrajsfieldformatter' => array(
      'label' => t('Call javascript file'),
      'field types' => array('file'),
      'description' => t('Takes the path given in a file field and uses a drupal_get_js()'),
    ),
  );

}

/**
* Implements hook_field_formatter_view().
*/
function extrajsfieldformatter_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {

	$element_iterator = 0;



	foreach($items as $item) {



		if (isset($item['uri'])) {
			$file_path_to_insert = trim(file_create_url($item['uri']));

			if (preg_match("/js$/", $file_path_to_insert)) {
				drupal_add_js($file_path_to_insert, array('type' => 'file', 'media' => 'all', 'preprocess' => false, 'every_page' => true));
				$element[$element_iterator]['#markup'] = "<!-- DEBUG JS adding $file_path_to_insert -->";
			}
			elseif (preg_match("/css$/", $file_path_to_insert))
			{
				drupal_add_css($file_path_to_insert);
				//$element[$element_iterator]['#markup'] = "<!-- DEBUG CSS adding $file_path_to_insert -->";
				$element[$element_iterator]['#markup'] = "<style type=\"text/css\" media=\"all\">@import url(\"$file_path_to_insert\");</style>";
			}

		}

		$element_iterator += 1;
	}

	if (isset($element)) {
		return $element;
	}
}
